CREATE TABLE IF NOT EXISTS identity.users ();
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS updated_by_id uuid NOT NULL;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS email varchar(50) NOT NULL UNIQUE;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS password_hash varchar(100) NOT NULL;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS phone_number varchar(20) NOT NULL;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT false;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS two_factor_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS first_name varchar(50);
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS last_name varchar(50);
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS landing_page varchar(100);
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS roles text;
ALTER TABLE identity.users ADD COLUMN IF NOT EXISTS clients text;
